### PR TITLE
Fix renaming issues + lint issues

### PR DESCRIPTION
**Pull request by jducro**
I updated some of your code to fix some issues in Storybook and to please eslint afterwards ;)

Please have a look I didn't break anything

### CODE REVIEW

**Comment by headzoo** [comment]
Everything looks good, though I'm not sure why the '.jsx' file extension is being used for import statements?

**Comment by headzoo** [comment]
Also, I don't find the `lint:js` command to be all that useful at the moment. Running it on my machine gives over 4,000 errors and warnings. I think because it's searching through /node_modules, and some other code we're not responsible for like /lib/styleguide/kss-assets/scrollspy.js.

**Comment by headzoo** [comment]
Also removing `this.state.popper` from Components/Columns/ItemPopper.jsx breaks other components which inherit from ItemPopper.

**Comment by jducro** [comment]
I use more `npm run lint:js -- --fix` the git hook is only scanning stages files.

I removed this.state.popper because it was set in componentDidMount, I guess we could set it at another time.

**Comment by headzoo** [comment]
> I removed this.state.popper because it was set in componentDidMount, I guess we could set it at another time.

In this case componentDidMount is the only time it can be set. The components which inherit from ItemPopper need access to its popper ref, which is only available after ItemPopper has been mounted. Forcing a re-render after mounting is intentional.

**Comment by jducro** [comment]
Ok, fair enough, I restored this code and added a `// eslint-disable-line` to prevent future warning about this setState in particular

**Comment by headzoo** [comment]
What about the jsx extensions when importing? Seems kind of pointless and ugly.

**Comment by jducro** [comment]
I'll try to prevent that in eslint configuration

**Comment by headzoo** [comment]
I came across this, which might help.

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md

**Comment by jducro** [comment]
We were using a shitty babel plugins that struggled to deal with extensions, `babel-plugin-module-resolver` works better

**Comment by headzoo** [comment]
Great, everything looks good now.

**Pull request merged**
