### PR TITLE
Moves src/Components/utils to src/utils

### PR DESCRIPTION
**Pull request by headzoo**
As the number of utility functions increases, it makes sense to treat them as "first class citizens" and put them in the `src/` directory so they can be imported using:

```js
import newId from 'utils/newId';
```

### CODE REVIEW

**Comment by jducro** [comment]
Shouldn't we add utils to .babelrc?

**Comment by headzoo** [comment]
I tried it with and without adding it to .babelrc, and it works either way. I think because `src/` is set as the root directory.

**Comment by jducro** [comment]
Oh right, so we probably don't even need the Component alias

**Comment by headzoo** [comment]
Yup, everything seems to work without the Components alias as well.

**Pull request merged**
